[crubit] Allow unstable Rust features required by Crubit.
Before this CL, the following command: `autoninja.sh -C out/rel
obj/third_party/rust-toolchain/lib/crubit/support/libforward_declare.rlib`
would fail (in presence of `enable_cpp_api_from_rust = true` in
`args.gn`):

```
error[E0725]: the feature `negative_impls` is not in the list of allowed features
 --> ../../third_party/rust-toolchain/lib/crubit/support/forward_declare.rs:4:12
  |
4 | #![feature(negative_impls)]
  |            ^^^^^^^^^^^^^^
```

The `forward_declare` support library is not needed by
`cc_bindings_from_rs` (only by `rs_bindings_from_cc`), but recent
Crubit changes mean that Crubit-provided `BUILD.gn` files cover all
support libraries.  See also
https://github.com/google/crubit/commit/b50b6d7ddce0e2940246b4daf69212dc766bc4ba

This CL provides the necessary opt-in and justification for using the
unstable Rust features when building Crubit support libraries.

Bug: 470466915
Change-Id: Ifd261b9e51b51987c4de948ab7c295837c333bd4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7997656
Reviewed-by: Hans Wennborg <hans@chromium.org>
Auto-Submit: Łukasz Anforowicz <lukasza@chromium.org>
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1653190}
NOKEYCHECK=True
GitOrigin-RevId: a93789b618a344b973d522057a4a9c6f0761c05b